### ISSUE TITLE
add feature to "ask user to chose between built-in repair method and your add-on" or maybe "auto backup before repairing" 

### ISSUE THREAD

**Issue by ijgnd** [Arthur-Milchior/anki-database-check-explained#2]
Your add-on description covers everything and warns prominently. I know that it's my responsibility to read the documentation and remember it.

But sometimes I'm inattentive: I forget that I still have an add-on installed/activated that I just wanted to try out. In theory I have a different base folder for this but sometimes I'm too lazy to use this.  Or you're in a panic when you encounter a database error and don't remember that you installed an experimental add-on. 

I think that other people might have this problem, too. Then someone will downvote your add-on. Other people who would benefit a lot from your add-on might be scared off by such a rating, etc.

This should be a quick fix: Maybe after a user clicks "Check Database" you could use [askUser](https://github.com/dae/anki/blob/master/aqt/utils.py#L100) to show a popup window if the built-in mechanism or yours should be used and that reminds the user to make a backup of the collection?

Maybe your add-on could even automatically make a backup before it tries to repair. Though I'm not sure about the latter idea because when people encounter an error they might open and close Anki many times and each time an old (good) backup is overwritten. This is especially relevant for older profiles that by default only kept 30 backups - the default for numBackups was only changed to 50 last year.

**Comment by Arthur-Milchior** [comment]
Actually, this give me a better (and simpler) idea.
The add-on won't actually change the database. It will only simulate the change, tell the user what will happen, and let anki's method do the actual change.
With one exception: finding duplicate cards, since anki does not (yet) do it

**Comment by aleksejrs** [comment]
Could it have caused this? https://anki.tenderapp.com/discussions/ankidesktop/39239-due-date-is-due-number-1970-or-2045

**Comment by Arthur-Milchior** [comment]
@aleksejrs can you please open another bug report. This seems unrelated to the current one. 
@ijgnd I'll close the current one if it's okay with you.

**Comment by ijgnd** [comment]
yes, this should be closed. 

I forgot this in my original post last year: thanks for sharing this add-on!
